Algo filter methods
toharush/trippin pull request #41
Opened 2023-06-06 13:42 UTC by YaronZandberg

### Currently Done:
1. Create all required functions before calling the algorithm.
2. Create required function which includes the algorithm call.
3. Create all algorithm logic methods.
4. Update necessary controllers. 

### Need to complete:
**Algorithm business:**
1. Client - We need to add a call to the method responsible to get the city center point - controllers/mapCalculation/getCityCenter. We need to add locate this call right after fetching all city coordinates by calling the GQL query. Only after doing this, we can send the city center to the server for running the algorithm.
2. Client - We need to send all necessary data from the client to the server, in order to run the algorithm successfully and manage to test it properly.
3. Replicator - We need to add openHour and closeHour in the DB. Right now these fields are empty, so the algorithm returns none activities, because "they aren't open".
4. Replicator - Like open and close hours, we need to add duration field to the DB to give this information to the algorithm.

**General business:**
1. Client - Finish all DatePicker issues and merge it to the main branch.
2. Client - Save client category preference in the store
3. Client - Add search feature to the side bar.
4. Client - Create a new page that shows a full planned trip.
5. Client - Create a new page that shows many full planned trips per user.
6. Client - Fix scroll bug in the map.
7. Server - Save full planned trip.
8. Server - Create a function that fetches all trips related to specific user.

2023-06-07 05:34 UTC, toharush requested changes

2023-06-07 05:34 UTC, toharush commented on apps/server/src/bestDayRouteAlgo/bestDayRouteConstants.ts
> +    static readonly EarthRadius: number = 6371;
Use turf in the function u use this.

2023-06-07 05:34 UTC, toharush commented on apps/server/src/bestDayRouteAlgo/bestDayRouteConstants.ts
> +    static readonly SplitToQuarter: number = 4;
Change it to const variable instead of class static variables for this and all the rest

2023-06-07 05:34 UTC, toharush commented on apps/server/src/controllers/MapCalculation.ts
> +) => points.filter(point => calculateDistance(point, center) <= radius);
Change it to work with turf or change the calculateDistance function to work with turf

2023-06-07 05:34 UTC, toharush commented on apps/server/src/utils/distance.sql
> +SELECT *
Remove this

2023-06-07 20:46 UTC, YaronZandberg commented on apps/client/src/index.tsx
> -import "./lib/console";
I didn't touch this file, but I got it back.

2023-06-07 20:48 UTC, YaronZandberg commented on apps/server/src/algorithm/calculateTrip.ts
> +        extraActivities: [],
I don't think that we have time to add this feature, both in client and server side, so I removed it.

2023-06-07 20:51 UTC, YaronZandberg commented on apps/server/src/app.ts
> +(async () =>
Done

2023-06-07 20:57 UTC, YaronZandberg commented on apps/server/src/bestDayRouteAlgo/bestDayRouteConstants.ts
> +    static readonly SplitToQuarter: number = 4;
Done

2023-06-07 20:59 UTC, YaronZandberg commented on apps/server/src/utils/distance.sql
> +SELECT *
Done.
Why this specific part was so critical to get rid of? 
We can remove this whole file don't you think?

2023-06-09 14:45 UTC, YaronZandberg commented on apps/server/src/algorithm/findStartActivity.ts
> +            const distance = calculateDistance(
You did it

2023-06-09 14:46 UTC, YaronZandberg commented on apps/server/src/bestDayRouteAlgo/bestDayRouteConstants.ts
> +    static readonly EarthRadius: number = 6371;
I didn't understand what did you mean here

2023-06-09 20:06 UTC, toharush approved these changes

2023-06-09 20:06 UTC, merged